### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by bufordtaylor** [beanieboi/heroku-nginx-puma-statsd#2]
I found your blog here: https://blog.codeship.com/how-to-deploy-nginx-on-heroku/

I attempted to setup my own version here: https://github.com/bufordtaylor/nginxtest

I'm attempting to proxy_pass my app from one heroku app to another. 

https://pacific-harbor-32411.herokuapp.com/test -> another-app.herokuapp.com

I think I'm reading the logs correctly, and it appears that the request is hitting puma first and nginx after.

```
2018-04-18T23:08:02.013509+00:00 heroku[router]: at=info method=GET path="/test" host=pacific-harbor-32411.herokuapp.com request_id=5f5cf59d-41c2-401b-b6df-e7c70156c400 fwd="24.63.55.10" dyno=web.1 connect=1ms service=5ms status=404 bytes=1954 protocol=https
2018-04-18T23:08:02.008852+00:00 app[web.1]: I, [2018-04-18T23:08:02.008741 #21]  INFO -- : [5f5cf59d-41c2-401b-b6df-e7c70156c400] Started GET "/test" for 24.63.55.10 at 2018-04-18 23:08:02 +0000
2018-04-18T23:08:02.009826+00:00 app[web.1]: F, [2018-04-18T23:08:02.009695 #21] FATAL -- : [5f5cf59d-41c2-401b-b6df-e7c70156c400]
2018-04-18T23:08:02.009915+00:00 app[web.1]: F, [2018-04-18T23:08:02.009857 #21] FATAL -- : [5f5cf59d-41c2-401b-b6df-e7c70156c400] ActionController::RoutingError (No route matches [GET] "/test"):
2018-04-18T23:08:02.009989+00:00 app[web.1]: F, [2018-04-18T23:08:02.009936 #21] FATAL -- : [5f5cf59d-41c2-401b-b6df-e7c70156c400]
2018-04-18T23:08:02.010090+00:00 app[web.1]: F, [2018-04-18T23:08:02.010027 #21] FATAL -- : [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
2018-04-18T23:08:02.010092+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2018-04-18T23:08:02.010095+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'
2018-04-18T23:08:02.010097+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `block in call'
2018-04-18T23:08:02.010099+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2018-04-18T23:08:02.010100+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
2018-04-18T23:08:02.010102+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'
2018-04-18T23:08:02.010104+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `call'
2018-04-18T23:08:02.010105+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
2018-04-18T23:08:02.010107+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
2018-04-18T23:08:02.010109+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
2018-04-18T23:08:02.010110+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
2018-04-18T23:08:02.010113+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
2018-04-18T23:08:02.010114+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
2018-04-18T23:08:02.010116+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
2018-04-18T23:08:02.010117+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
2018-04-18T23:08:02.010118+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
2018-04-18T23:08:02.010120+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
2018-04-18T23:08:02.010121+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
2018-04-18T23:08:02.010123+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
2018-04-18T23:08:02.010124+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
2018-04-18T23:08:02.010126+00:00 app[web.1]: [5f5cf59d-41c2-401b-b6df-e7c70156c400] vendor/bundle/ruby/2.3.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2018-04-18T23:08:02.010956+00:00 app[web.1]: measure#nginx.service=0.003 request_id=5f5cf59d-41c2-401b-b6df-e7c70156c400
2018-04-18T23:08:02.121291+00:00 app[web.1]: measure#nginx.service=0.002 request_id=d5a46241-5640-4e20-8d01-d2849fed93ec

```

You spot anything I'm doing wrong?

**Comment by beanieboi** [comment]
Hey

Sorry for the late response. Heroku is hitting nginx first and nginx is a reverse proxy for Rails. I can’t spot anything obvious from the stack trace :(
